"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FOOTER_BOTTOM_MARGIN = exports.MARGIN_FROM_INPUT_ANDROID = exports.MARGIN_FROM_INPUT_IOS = void 0;
var MARGIN_FROM_INPUT_IOS = 28;
exports.MARGIN_FROM_INPUT_IOS = MARGIN_FROM_INPUT_IOS;
var MARGIN_FROM_INPUT_ANDROID = 20;
exports.MARGIN_FROM_INPUT_ANDROID = MARGIN_FROM_INPUT_ANDROID;
var FOOTER_BOTTOM_MARGIN = 20;
exports.FOOTER_BOTTOM_MARGIN = FOOTER_BOTTOM_MARGIN;
