"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var NativeReactNativeHybridApp_1 = require("./NativeReactNativeHybridApp");
var HybridAppModule = {
    isHybridApp: function () {
        return NativeReactNativeHybridApp_1.default.isHybridApp();
    },
    shouldUseStaging: function (isStaging) {
        NativeReactNativeHybridApp_1.default.shouldUseStaging(isStaging);
    },
    closeReactNativeApp: function (_a) {
        var shouldSetNVP = _a.shouldSetNVP;
        NativeReactNativeHybridApp_1.default.closeReactNativeApp(shouldSetNVP);
    },
    completeOnboarding: function (_a) {
        var status = _a.status;
        NativeReactNativeHybridApp_1.default.completeOnboarding(status);
    },
    switchAccount: function (_a) {
        var newDotCurrentAccountEmail = _a.newDotCurrentAccountEmail, authToken = _a.authToken, policyID = _a.policyID, accountID = _a.accountID;
        NativeReactNativeHybridApp_1.default.switchAccount(newDotCurrentAccountEmail, authToken, policyID, accountID);
    },
    sendAuthToken: function (_a) {
        var authToken = _a.authToken;
        NativeReactNativeHybridApp_1.default.sendAuthToken(authToken);
    },
    getHybridAppSettings: function () {
        return NativeReactNativeHybridApp_1.default.getHybridAppSettings();
    },
    getInitialURL: function () {
        return NativeReactNativeHybridApp_1.default.getInitialURL();
    },
    onURLListenerAdded: function () {
        NativeReactNativeHybridApp_1.default.onURLListenerAdded();
    },
    signInToOldDot: function (_a) {
        var autoGeneratedLogin = _a.autoGeneratedLogin, autoGeneratedPassword = _a.autoGeneratedPassword, authToken = _a.authToken, email = _a.email, policyID = _a.policyID, signingInWithSAML = _a.signingInWithSAML;
        NativeReactNativeHybridApp_1.default.signInToOldDot(autoGeneratedLogin, autoGeneratedPassword, authToken, email, policyID, signingInWithSAML);
    },
    signOutFromOldDot: function () {
        NativeReactNativeHybridApp_1.default.signOutFromOldDot();
    },
    clearOldDotAfterSignOut: function () {
        NativeReactNativeHybridApp_1.default.clearOldDotAfterSignOut();
    },
};
exports.default = HybridAppModule;
